id: PB154999D
initial_creation_type: input
source_metadata:
  title: Dzogchen Pema Rigdzin Series
  language: zh
  description: Texts by Dzogchen Pema Rigdzin (rdzogs chen padma rig 'dzin, 1625–1697),
    the great adept who founded Dzogchen Monastery in Kham.
  volume:
    ca7503956fab4938900045ca91f76fe6:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
created_at: '2022-02-28T23:11:42.476913'
last_modified_at: '2022-02-28T23:11:42.476915'
